<html>
    <head>
        <title><?php if (isset($_title)) : strtoupper(htmlspecialchars($_title)); endif; ?></title>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" media="all" href="css/permanent-12.css">
        <link rel="stylesheet" type="text/css" media="all" href="css/main.css">
        <link rel="stylesheet" type="text/css" media="all" href="css/animations.css">

        <?php if (isset($_style) && $_style == 'fade-in') : ?>
        <link rel="stylesheet" type="text/css" media="all" href="css/fade-in.css" />
        <?php elseif (isset($_style) && $_style == 'fade-in-out') : ?>
        <link rel="stylesheet" type="text/css" media="all" href="css/fade-in.css" />
        <link rel="stylesheet" type="text/css" media="all" href="css/fade-in-out.css" />
        <?php endif; ?>

        <script type="text/javascript" src="js/clock.js"></script>
    </head>
    <body>
        <ul id="streams" class="streams">
        <?php if (isset($_categories)) : ?>
            <?php foreach ($_categories as $category) : ?>
            <li><a href="<?= htmlspecialchars($category['url']) ?>"><?= htmlspecialchars($category['name1']) ?></a></li>
            <?php endforeach; ?>
        <?php endif; ?>
        </ul>
        <ul class="streams">
            <li><a href="/celebrity-leader-board">Celebrity Leader Board</a></li>
        </ul>
    </body>
</html>
